### ISSUE TITLE
Help ! How to use the package?

### ISSUE THREAD

**Issue by bioinformaticspcj** [ncbi/EvoGeneX#1]
Dear authors,

Thanks for developing such a useful software. Now I want to use it to find the gene  expression evolution in my species RNA-seq data. But I do not know how to produce the inputs (like regime_global.csv, HD_M_FBgn0000008.csv ) for EvoGeneX. 

Looking forward to your timely reply.
Best wishes.

**Comment by soumitrakp** [comment]
EvoGeneX needs three inputs:
1. The phylogenetic tree with branch length denoting evolutionary time. You can write in newick format.
2. The information about which part of the tree is under what regime of the OU process (please see the methods section of our biorxiv paper). If there is a single regime, like in the example, you can specify 'global' for all nodes. For a tip, you can just specify tip-label and 'global' on a row in the comma separated file. For an internal node, you can specify the node in the form tip1.tip2 where the node is the most recent common ancestor of tip1 and tip2.
3. The gene expression data. You can specify the expression values in a row for each species. The first column in the row is the tip label for the species followed by the expression values for the replicates.
Let me know if I could be of any further help.

**Comment by bioinformaticspcj** [comment]
Dear the authors,
Many thanks for providing me with the&nbsp;instructions. By now, I still have a question that does the gene expression data reffer to only one gene expression data and if I want to test 1000 or more genes, I should write a script to do so?


Best,




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Soumitra Pal"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 晚上9:51
收件人:&nbsp;"ncbi/EvoGeneX"<EvoGeneX@noreply.github.com&gt;;
抄送:&nbsp;"Monkeyjun"<2532090267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ncbi/EvoGeneX] Help ! How to use the package? (#1)





 
EvoGeneX needs three inputs:
  
The phylogenetic tree with branch length denoting evolutionary time. You can write in newick format.
 
The information about which part of the tree is under what regime of the OU process (please see the methods section of our biorxiv paper). If there is a single regime, like in the example, you can specify 'global' for all nodes. For a tip, you can just specify tip-label and 'global' on a row in the comma separated file. For an internal node, you can specify the node in the form tip1.tip2 where the node is the most recent common ancestor of tip1 and tip2.
 
The gene expression data. You can specify the expression values in a row for each species. The first column in the row is the tip label for the species followed by the expression values for the replicates.
 Let me know if I could be of any further help.

**Comment by soumitrakp** [comment]
You need not create a new script and run the script multiple times. Instead, you could repeat the call to function `fit` multiple times.
Let us consider `example1` in `examples` directory:
```
data = read.csv('../data/HD_M_FBgn0000008.csv', row.names=1, stringsAsFactors=F)
evog <- EvoGeneX()
evog$setTree('../data/drosophila9.newick')
evog$setRegimes('../data/regime_global.csv')
res = evog$fit(data, alpha=0.1, gamma.sq=0.01)
print(res)
```
You can modify it to call setTree and setRegimes only once and call fit multiple times as follows:
```
evog <- EvoGeneX()
evog$setTree('../data/drosophila9.newick')
evog$setRegimes('../data/regime_global.csv')
for (gene in gene_list) {
data = read.csv(paste0('../data/HD_M_', gene, '.csv', row.names=1, stringsAsFactors=F)
res = evog$fit(data, alpha=0.1, gamma.sq=0.01)
print(res)
}
```
Let us know if you need any other information. Thank you.
