### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by pedro-mmartins** [ncbi/EvoGeneX#2]
Dear authors,

I tried to install EvoGeneX, but error messages keep coming up and I'm not sure on how to deal with them.

When I try to run the installation pipeline on MacOS (with R version 4.1 and devtools up to date), I have this:
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ./evogenex_brown.hpp:34:9: error: reference member 'dat' binds to a temporary object whose lifetime would be shorter than the lifetime of the constructed object

My colleagues tried it on Windows (same R version) and got this message:
In i.p(...) :
  installation of package ‘C:/Users/vansc/AppData/Local/Temp/RtmpaO8rw3/file7ad860557a09/EvoGeneX_0.0.0.2.tar.gz’ had non-zero exit status

What should we do?
Thanks!
Pedro

**Comment by soumitrakp** [comment]
Hi Pedro,
Thanks for your interest in EvoGeneX. We have tried so far on Linux and not on Mac or Windows. I will look into installing it on Mac and Windows. However, could you please do a favor by trying it on a Linux system?
Regards,
Soumitra

**Comment by pedro-mmartins** [comment]
Hello again!

It has worked. Thanks for the swift response.

Best,
Pedro
